# See https://pre-commit.com for more information
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/wazo-platform/wazo-git-hooks
  rev: 1.1.1
  hooks:
  - id: wazo-copyright-check

- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    language_version: "3.11"
    additional_dependencies: ["types-mock", "types-pytz", "types-requests"]
