#!/usr/bin/env python

import subprocess
import sys

from starpy import manager

sys.path.append("lib/python")
from asterisk.asterisk import Asterisk
from asterisk.TestCase import TestCase

class SccpTest(TestCase):

    def __init__(self):
        TestCase.__init__(self)
        self.create_asterisk(1)

    def run(self):
        TestCase.run(self)
        self.passed = False

        for ast in self.ast:
            ast.cli_exec("module load chan_sccp.so")

        cmd = [ 'sccpp', '-c', '0' ]

        try:
            retcode = subprocess.call(cmd)
        except OSError:
            return

        if retcode == 0:
            self.passed = True
        else:
            self.passed = False

def main():
    test = SccpTest()
    
    test.start_asterisk()
    test.run()
    test.stop_asterisk()

    if not test.passed:
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main() or 0)

#set sw=4 ts=4 expandtab textwidth=79
